deployment:
  tasks:
    # Go to the Laravel project directory
    - export DEPLOYPATH=/home/obppayco/laravel-project

    # Pull latest code
    - /usr/local/cpanel/3rdparty/bin/git pull

    # Install vendor packages
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # Set permissions
    - chmod -R 775 storage bootstrap/cache

    # Laravel optimization
    - php artisan migrate --force
    - php artisan optimize:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
